replicaCount: 2

image:
  repository: lbdr1acr.azurecr.io/hello
  tag: "build-13"    # CI updates this automatically
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80
  targetPort: 8080

resources:
  requests:
    cpu: 50m
    memory: 64Mi

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  cpu: 60
