apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argocd-application-controller-extra
rules:
  - apiGroups: ["acn.azure.com"]
    resources: ["overlayextensionconfigs"]
    verbs: ["get","list","watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argocd-application-controller-extra-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argocd-application-controller-extra
subjects:
  - kind: ServiceAccount
    name: argocd-application-controller
    namespace: agro
