name: Build, Scan, Push, GitOps Bump

on:
  push:
    branches: ["main"]
  #workflow_dispatch: {}

env:
  ACR_NAME: ${{ secrets.ACR_NAME }}
  IMAGE_NAME: hello

jobs:
  build-scan-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # To commit version bump

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set image tag
        id: vars
        run: echo "TAG=build-${GITHUB_RUN_NUMBER}" >> $GITHUB_OUTPUT

      - name: Azure login (SP)
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: ACR login
        run: |
          TOKEN=$(az acr login -n $ACR_NAME --expose-token --output tsv --query accessToken)
          docker login $ACR_NAME.azurecr.io -u 00000000-0000-0000-0000-000000000000 -p $TOKEN

      - name: Build Docker image
        run: |
          docker build -t $ACR_NAME.azurecr.io/$IMAGE_NAME:${{ steps.vars.outputs.TAG }} ./app

      - name: Trivy filesystem scan (app)
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: fs
          scan-ref: ./app
          format: table
          exit-code: '0'

      - name: Trivy image scan (vulns)
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: $ACR_NAME.azurecr.io/$IMAGE_NAME:${{ steps.vars.outputs.TAG }}
          format: table
          exit-code: '0'

      - name: Push Docker image to ACR
        run: |
          docker push $ACR_NAME.azurecr.io/$IMAGE_NAME:${{ steps.vars.outputs.TAG }}

      - name: Checkov (K8s/Helm/IaC)
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: charts/hello
          config_file: policy/checkov.yaml
        continue-on-error: true

      - name: GitOps bump Helm values with new tag
        run: |
          sed -i "s/^  tag: \".*\"/  tag: \"${{ steps.vars.outputs.TAG }}\"/" charts/hello/values.yaml
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add charts/hello/values.yaml
          git commit -m "chore(gitops): bump image tag to ${{ steps.vars.outputs.TAG }}"
          git push
